"use client";
import { useState } from "react";
import { AlertCircle,ArrowRight,CheckCircle2,LoaderCircle,RotateCcw,Search } from "lucide-react";
import Link from "next/link";
type Result={score:number;confidence:number;mentions:number;total:number;opportunities:number;summary:string;providers:string[];failures:{provider:string;error:string}[];brand:{name:string}};
function confidenceLabel(value:number){return value>=70?"High confidence":value>=40?"Medium confidence":"Low confidence"}
export function Checker(){
 const [url,setUrl]=useState(""),[state,setState]=useState<"idle"|"loading"|"done"|"error">("idle"),[result,setResult]=useState<Result|null>(null),[error,setError]=useState("");
 async function run(e:React.FormEvent){e.preventDefault();if(!url.trim())return;setState("loading");setError("");try{const response=await fetch("/api/check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The visibility check failed.");setResult(data);setState("done")}catch(err){setError(err instanceof Error?err.message:"The visibility check failed.");setState("error")}}
 function reset(){setState("idle");setResult(null);setError("")}
 return <div className="checker-card">{(state==="idle"||state==="loading")&&<><form onSubmit={run}><Search/><input aria-label="Website URL" value={url} onChange={e=>setUrl(e.target.value)} placeholder="yourwebsite.com" disabled={state==="loading"}/><button className="button" disabled={state==="loading"}>{state==="loading"?<><LoaderCircle className="spin"/> Checking live AI answers…</>:<>Check my brand <ArrowRight/></>}</button></form><div className="checker-foot"><span>We’ll check questions like:</span><b>“Best tools for my team”</b><b>“Top alternatives in my category”</b><b>“What should I use for…”</b></div>{state==="loading"&&<p className="live-note">This can take up to a minute while configured AI engines answer.</p>}</>}{state==="error"&&<div className="checker-error"><AlertCircle/><div><b>We couldn’t complete the check</b><p>{error}</p></div><button className="button outline" onClick={reset}><RotateCcw/>Try again</button></div>}{state==="done"&&result&&<div className="quick-result"><div className="score-block"><div className="score-ring"><b>{result.score}</b><span>/100</span></div><small className="confidence-tag">{confidenceLabel(result.confidence)}</small></div><div><span className="result-label"><CheckCircle2/> Live scan complete</span><h3>{result.summary}</h3><p>We found {result.mentions} mentions in {result.total} answers across {result.providers.length} engine{result.providers.length===1?"":"s"}. {result.opportunities} prompt opportunities are ready.{result.failures?.length?` ${result.failures.length} provider request(s) could not be completed.`:""}</p></div><div className="result-actions"><Link href="/app" className="button">See full results <ArrowRight/></Link><button onClick={reset}>Check another site</button></div></div>}</div>
}
